"""
train.py
--------
Trains a genuine scikit-learn RandomForestClassifier for leak detection,
replacing the hand-coded if/else decision tree logic in leak_model.js
with a model that actually learned from data.

Usage:
    python3 train.py

Outputs:
    model/leak_model.pkl       <- trained model, ready to load with joblib
    model/metrics.md           <- accuracy, precision/recall, confusion matrix
    model/feature_importance.png
"""

import pandas as pd
import numpy as np
import joblib
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)

FEATURES = ["currentloss", "rollingmeanloss", "rollingstdloss", "consecutivehigh"]
TARGET = "is_leak"

DATA_PATH = "data/synthetic_leak_data.csv"
MODEL_DIR = "model"


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)

    # 1. Load data
    df = pd.read_csv(DATA_PATH)
    X = df[FEATURES]
    y = df[TARGET]

    # 2. Train/test split (stratified to preserve leak/no-leak ratio)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # 3. Train a real Random Forest (matches the "11 trees" claim in
    #    AI_ENGINE.md, but this time actually trained on data)
    model = RandomForestClassifier(
        n_estimators=11,
        max_depth=6,
        min_samples_leaf=5,
        class_weight="balanced",   # accounts for leak being the minority class
        random_state=42,
    )
    model.fit(X_train, y_train)

    # 4. Evaluate
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred, target_names=["no_leak", "leak"])

    # 5. Save model
    model_path = os.path.join(MODEL_DIR, "leak_model.pkl")
    joblib.dump(model, model_path)

    # 6. Feature importance plot
    importances = model.feature_importances_
    plt.figure(figsize=(6, 4))
    plt.barh(FEATURES, importances, color="#2563eb")
    plt.xlabel("Importance")
    plt.title("Leak Detection - Feature Importance")
    plt.tight_layout()
    fi_path = os.path.join(MODEL_DIR, "feature_importance.png")
    plt.savefig(fi_path, dpi=150)
    plt.close()

    # 7. Write metrics.md
    metrics_md = f"""# Leak Detection Model — Training Metrics

## Model
- Algorithm: RandomForestClassifier (scikit-learn)
- Trees: 11 (n_estimators)
- Max depth: 6
- Class weighting: balanced (leak events are ~17% of ticks)

## Dataset
- Source: synthetic, generated by `generate_data.py`
- Simulates realistic flowRate / reservoirLevel time series with injected
  leak events at random points in each session
- Total rows: {len(df)}
- Train/test split: 80/20, stratified
- Positive class (leak) ratio: {y.mean():.2%}

## Test Set Performance

| Metric    | Value |
|-----------|-------|
| Accuracy  | {acc:.4f} |
| Precision | {prec:.4f} |
| Recall    | {rec:.4f} |
| F1 Score  | {f1:.4f} |

## Confusion Matrix

```
                Predicted
                No Leak   Leak
Actual No Leak    {cm[0][0]:<8}  {cm[0][1]:<6}
Actual Leak       {cm[1][0]:<8}  {cm[1][1]:<6}
```

## Full Classification Report

```
{report}
```

## Feature Importance

See `feature_importance.png`. Top predictive features (by learned importance):

{chr(10).join(f"- **{f}**: {imp:.3f}" for f, imp in sorted(zip(FEATURES, importances), key=lambda x: -x[1]))}

## Notes

This model was trained on synthetic data as a proof-of-concept to validate
the ML pipeline end-to-end (feature engineering -> training -> evaluation ->
serialized artifact). It replaces the placeholder hand-coded decision logic
in `dashboard/src/ai/leak_model.js` with a model that was genuinely fit to
data rather than manually threshold-tuned.

**Next step (documented in architecture.md):** retrain on real Firebase-logged
sensor history once sufficient production data is collected, and serve via
a REST API (FastAPI) as described in the system architecture, rather than
loading the .pkl directly into the browser.
"""

    with open(os.path.join(MODEL_DIR, "metrics.md"), "w") as f:
        f.write(metrics_md)

    # 8. Console summary
    print("Training complete.")
    print(f"  Accuracy:  {acc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1:        {f1:.4f}")
    print(f"Model saved to: {model_path}")
    print(f"Metrics saved to: {MODEL_DIR}/metrics.md")


if __name__ == "__main__":
    main()
